version: "3"

services:
  database:
    container_name: database
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=absensi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - absensi

networks:
  absensi:

volumes:
  pgdata: