version: '3.8'

services:
  database:
    build: 
      context: ./postgres  # Gunakan Dockerfile dari folder postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    build: 
      context: ./app  # Gunakan Dockerfile dari folder app
    container_name: flask_container
    restart: always
    depends_on:
      - database
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load variabel dari .env
    volumes:
      - ./app:/app