name: Continuous Integration

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]
    
jobs:
    build-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose
            
            - name: Run Containers
              run: |
                sudo docker compose up -d
            
            - name: Wait for Flask to be ready
              run: |
                for i in {1..10}; do
                  if curl -sSf http://localhost:5000 > /dev/null; then
                    echo "Flask is ready!"
                    exit 0
                  fi
                  echo "Waiting for Flask to start..."
                  sleep 3
                done
                echo "Flask did not start in time" && exit 1

            - name: testing
              run: |
                python3 tests/test.py

    build-push:
        needs: build-test
        name: Build and Push Image To DockerHub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and Push Flask App
              uses: docker/build-push-action@v4
              with:
                  context: ./app
                  file: ./app/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:${{ github.run_number }}
            
            - name: Build and Push Postgres
              uses: docker/build-push-action@v4
              with:
                  context: ./postgres
                  file: ./postgres/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres:${{ github.run_number }}
            

    